spring:
  application:
    name: banku-engine-service
  profiles:
    active: local
  data:
    mongodb:
      uri: ${spring.data.mongodb.uri}
  kafka:
    bootstrap-servers: ${spring.kafka.bootstrap-servers}
    consumer:
      group-id: banku-user-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

jwt:
  secret: ${jwt.secret}

server:
  port: 8083

logging:
  level:
    com: DEBUG
    org.springframework.security: INFO 

openai:
  api-key: ${openai.api-key}
  model: ${openai.model}
  prompts:
    alert: "Analyze the provided financial transaction and account data.\n\nGenerate financial alerts based on the following criteria:\n- **Unusual Spending Patterns**: Significant deviations from historical spending behavior.\n- **Duplicate Transactions**: Identical or highly similar transactions occurring within a short time frame.\n- **Low Account Balances**: Balances dropping below user-defined or system-defined critical thresholds.\n- **Potential Fraud Indicators**: Transactions flagged by common fraud heuristics (e.g., unusual locations, rapid frequency, abnormal transaction amounts).\n- **Unusual Account Activity**: Activities such as sudden large deposits or withdrawals, frequent account access from varying locations, or abnormal login behaviors.\n\nReturn the results exclusively as a valid JSON array of alert objects, strictly adhering to this format:\n[\n    {\n        \"type\": \"CRITICAL|WARNING|INFO\",\n        \"title\": \"Concise alert title\",\n        \"description\": \"Detailed, clear, and actionable description of the detected alert.\"\n    }\n]\n\nEnsure no additional text, explanations, or data beyond the JSON array is included.\n\nGenerate everything in spanish." 
    recommendation: "Analyze the provided financial transaction and account data.\n\nGenerate personalized financial recommendations in the following specific areas:\n- **Savings Opportunities** (type: SAVINGS): Identify actionable ways to reduce expenses or increase savings based on spending patterns.\n- **Investment Strategies** (type: INVESTMENT): Suggest suitable investment options or adjustments considering financial goals and risk tolerance.\n- **Budgeting Advice** (type: BUDGETING): Provide recommendations to optimize spending and manage monthly budgets effectively.\n- **Debt Management** (type: DEBT_MANAGEMENT): Recommend strategies to efficiently manage or reduce existing debt obligations.\n\nReturn the recommendations exclusively as a valid JSON array of recommendation objects, strictly adhering to this format:\n[\n    {\n        \"title\": \"Concise recommendation title\",\n        \"description\": \"Detailed, clear, and actionable explanation of the recommendation.\",\n        \"type\": \"SAVINGS|INVESTMENT|BUDGETING|DEBT_MANAGEMENT\"\n    }\n]\n\nDo not include any additional text, explanations, or data beyond the JSON array.\n\nGenerate everything in spanish."

springdoc:
  swagger-ui:
    path: /api/v1/engine/swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    filter: true
  api-docs:
    path: /api/v1/engine/v3/api-docs
  show-actuator: true
  packages-to-scan: com.banku.engineservice.controller
  paths-to-match: /api/v1/** 
