spring:
  application:
    name: banku-engine-service
  profiles:
    active: local
  data:
    mongodb:
      uri: ${spring.data.mongodb.uri}
  kafka:
    client:
      id: ${spring.kafka.client.id}
    consumer:
      group-id: ${spring.kafka.consumer.group-id}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    properties:
      security.protocol: ${spring.kafka.properties.security.protocol}
      sasl.mechanism: ${spring.kafka.properties.sasl.mechanism}
      sasl.jaas.config: ${spring.kafka.properties.sasl.jaas.config}

jwt:
  secret: ${jwt.secret}

server:
  port: 8083

logging:
  level:
    com: DEBUG
    org.apache.kafka: INFO
    org.springframework.security: INFO 

openai:
  api-key: ${openai.api.key}
  model: ${openai.model}
  prompts:
    alert: ${openai.prompts.alert}
    recommendation: ${openai.prompts.recommendation}

springdoc:
  swagger-ui:
    path: /api/v1/engine/swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    filter: true
  api-docs:
    path: /api/v1/engine/v3/api-docs
  show-actuator: true
  packages-to-scan: com.banku.engineservice.controller
  paths-to-match: /api/v1/** 
